In [10]:
import numpy as np
from numpy.linalg import eig

In [11]:
A = np.array([1, 3])
B = np.array([[1, -1],[6, -4]])

In [12]:
a,b = np.linalg.eig(B)

In [13]:
a

array([-1., -2.])

In [14]:
b

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

In [15]:
A/np.linalg.norm(A)

array([0.31622777, 0.9486833 ])