In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

In [44]:
a1 = np.array([[23, 50],[7, 12]])
a2 = np.array([[57, 67],[99, 43]])
a3 = np.array([[75, 21],[57, 12]])
a4 = np.array([[87, 26],[18, 84]])

In [46]:
aa = np.array([[a1, a2],[a3, a4]])

In [47]:
aa

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [51]:
aa.shape

(2, 2, 2, 2)

In [39]:
A = np.array([[23, 50, 19],[7, 12, 109],[57, 67, 98]])

In [40]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [49]:
A.shape

(3, 3)

In [41]:
B = np.array([[17, 22, 19]])

In [42]:
B

array([[17, 22, 19]])

In [50]:
B.shape

(1, 3)