In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,
              **options)

In [4]:
A = np.array([17, 22, 19])

In [5]:
A = np.array([17, 22, 19])
B = np.array([10, 20, 11])
C = np.array([5, 12, 9])

In [6]:
A + B

array([27, 42, 30])

In [7]:
B - C

array([5, 8, 2])

In [18]:
A @ C

520

In [9]:
A * B

array([170, 440, 209])

In [10]:
np.linalg.norm(A)

33.67491648096547

In [19]:
cos_theta = A @ B / (np.linalg.norm(A) * np.linalg.norm(B))
cos_theta

0.9759590023331435

In [20]:
u = ([2, 5])
v = ([3, 1])