In [1]:
import numpy as np

In [2]:
a1 = np.array([[23, 50],[7,  12]])
a2 = np.array([[75, 21],[57, 12]])
a3 = np.array([[57, 67],[99, 43]])
a4 = np.array([[87, 26],[18, 84]])

In [3]:
aa = np.array([[a1, a2],[a3, a4]])

In [4]:
aa

array([[[[23, 50],
         [ 7, 12]],

        [[75, 21],
         [57, 12]]],


       [[[57, 67],
         [99, 43]],

        [[87, 26],
         [18, 84]]]])

In [5]:
aa.shape

(2, 2, 2, 2)

In [6]:
A = np.array([[23, 50, 19], [7, 12, 109], [57, 67,98]])
B = np.array([17, 22, 19])

In [7]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [8]:
B

array([17, 22, 19])

In [9]:
A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [10]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [11]:
np.linalg.det(A)

131344.0000000002

In [12]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])